window.WORLD = {
    seaColor: 0x0e4a7a,
    shoreColor: 0xe3c98a,
    regions: [
        { id: "r_north_cap", label: "The Northern Ice Cap", x: 0.4600, y: 0.1100, biome: "snow", color: 0xf2f6ff, landmark: true },
        { id: "r_ice_shelf", label: "The Western Ice Shelf", x: 0.2450, y: 0.2250, biome: "ice", color: 0xcdeff2, landmark: false },
        { id: "r_ne_tundra", label: "The Northeast Tundra", x: 0.7100, y: 0.2050, biome: "tundra", color: 0xb9c4c0, landmark: false },
        { id: "r_north_marsh", label: "The Northern Marshes", x: 0.4850, y: 0.3050, biome: "wetland", color: 0x3a5f4e, landmark: false },
        { id: "r_nw_city", label: "Northwest City", x: 0.1550, y: 0.3500, biome: "urban", color: 0x6e7f78, landmark: false },
        { id: "r_west_metro", label: "West Harbor Metropolis", x: 0.0600, y: 0.4550, biome: "urban", color: 0x7d8794, landmark: true },
        { id: "r_west_vale", label: "The Western Vale", x: 0.2150, y: 0.4450, biome: "orchard", color: 0x4f7a35, landmark: true },
        { id: "r_rivermouth", label: "Rivermouth City", x: 0.0950, y: 0.5550, biome: "urban-river", color: 0x5a7a86, landmark: true },
        { id: "r_west_capital", label: "The Western Capital", x: 0.2450, y: 0.5450, biome: "urban", color: 0x7d8794, landmark: false },
        { id: "r_high_pass", label: "The High Pass", x: 0.3500, y: 0.4550, biome: "mountain", color: 0x6b6f5c, landmark: true },
        { id: "r_frontier", label: "The Far Frontier", x: 0.2250, y: 0.6550, biome: "frontier", color: 0x7d8a5a, landmark: true },
        { id: "r_desert", label: "The Central Desert", x: 0.4150, y: 0.6100, biome: "desert", color: 0xd9a066, landmark: false },
        { id: "r_karst", label: "The Karst Hollows", x: 0.5000, y: 0.6000, biome: "rock", color: 0x8a7d68, landmark: false },
        { id: "r_archive_qtr", label: "The Archive Quarter", x: 0.6600, y: 0.5750, biome: "oldtown", color: 0x5a4a6a, landmark: false },
        { id: "r_central_village", label: "Central Village", x: 0.5850, y: 0.6600, biome: "village", color: 0x567f30, landmark: true },
        { id: "r_old_quarter", label: "The Old Quarter", x: 0.7300, y: 0.6500, biome: "oldtown", color: 0x5a4a6a, landmark: false },
        { id: "r_midtown", label: "Midtown", x: 0.6700, y: 0.7400, biome: "urban", color: 0x7d8794, landmark: false },
        { id: "r_undercity", label: "The Undercity", x: 0.5800, y: 0.8200, biome: "urban", color: 0x6a6470, landmark: false },
        { id: "r_commons", label: "The Commons", x: 0.5000, y: 0.7300, biome: "urban", color: 0x7d8794, landmark: false },
        { id: "r_lowland_fields", label: "The Lowland Fields", x: 0.4000, y: 0.8200, biome: "farmland", color: 0x8fae52, landmark: false },
        { id: "r_spire_dist", label: "The Spire District", x: 0.7600, y: 0.8100, biome: "urban", color: 0x7d8794, landmark: false },
        { id: "r_citadel", label: "The Grand Citadel", x: 0.6700, y: 0.8900, biome: "citadel", color: 0x7a6a4a, landmark: true },
        { id: "r_gardens", label: "The Botanical Gardens", x: 0.5600, y: 0.9200, biome: "garden", color: 0x4a8f6a, landmark: false },
        { id: "r_south_wilds", label: "The Southern Wilds", x: 0.4300, y: 0.9500, biome: "forest", color: 0x244d18, landmark: true },
        { id: "r_east_shore", label: "The Eastern Shore", x: 0.8400, y: 0.6700, biome: "coast", color: 0xe6c78a, landmark: true },
        { id: "r_tropic_isle", label: "The Tropical Isle", x: 0.9400, y: 0.5600, biome: "tropical", color: 0x2f8f5a, landmark: true }
    ],
    routes: [
        { from: "r_north_cap", to: "r_ice_shelf" },
        { from: "r_north_cap", to: "r_ne_tundra" },
        { from: "r_north_cap", to: "r_north_marsh" },
        { from: "r_north_marsh", to: "r_west_vale" },
        { from: "r_ice_shelf", to: "r_nw_city" },
        { from: "r_nw_city", to: "r_west_metro" },
        { from: "r_nw_city", to: "r_west_vale" },
        { from: "r_west_metro", to: "r_rivermouth" },
        { from: "r_rivermouth", to: "r_west_capital" },
        { from: "r_west_vale", to: "r_west_capital" },
        { from: "r_west_capital", to: "r_high_pass" },
        { from: "r_west_capital", to: "r_frontier" },
        { from: "r_frontier", to: "r_desert" },
        { from: "r_high_pass", to: "r_desert" },
        { from: "r_desert", to: "r_karst" },
        { from: "r_karst", to: "r_central_village" },
        { from: "r_central_village", to: "r_archive_qtr" },
        { from: "r_central_village", to: "r_commons" },
        { from: "r_archive_qtr", to: "r_old_quarter" },
        { from: "r_old_quarter", to: "r_midtown" },
        { from: "r_old_quarter", to: "r_east_shore" },
        { from: "r_commons", to: "r_midtown" },
        { from: "r_midtown", to: "r_citadel" },
        { from: "r_midtown", to: "r_undercity" },
        { from: "r_midtown", to: "r_spire_dist" },
        { from: "r_undercity", to: "r_citadel" },
        { from: "r_spire_dist", to: "r_citadel" },
        { from: "r_commons", to: "r_lowland_fields" },
        { from: "r_lowland_fields", to: "r_citadel" },
        { from: "r_citadel", to: "r_gardens" },
        { from: "r_gardens", to: "r_commons" },
        { from: "r_gardens", to: "r_south_wilds" },
        { from: "r_citadel", to: "r_east_shore" },
        { from: "r_east_shore", to: "r_tropic_isle", land: false }
    ]
};
